<h1>Créer un nouvel article</h1>
<hr>
<form method="POST">
	<div class="form-group">
	
		<input type="text" class="form-control" id="title" name="title" placeholder="Titre" value="">
	</div>
	<div class="form-group">
	
		<input type="text" class="form-control" id="content" name="content" placeholder="Content" value="">
	</div>
	<div class="form-group">
		<input type="text" class="form-control" id="date" name="date" placeholder="Date" value="">
	</div>
	<div class="form-group">
	
		<input type="text" class="form-control" id="image" name="image" placeholder="Image" value="">
	</div>
	<button type="submit" name="action" class="btn btn-primary" value="create">Créer</button>
</form>