<h1>Créer un sponsor</h1>
<hr>
<form method="POST">
	<div class="form-group">
		<label for="nom">nom</label>
		<input type="text" class="form-control" id="nom" name="nom" placeholder="nom" value="">
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<input type="text" class="form-control" id="description" name="description" placeholder="description" value="">
	</div>
	<div class="form-group">
		<label for="adresse">Adresse</label>
		<input type="text" class="form-control" id="adresse" name="adresse" placeholder="adresse" value="">
	</div>
	<div class="form-group">
		<label for="participation">Participation</label>
		<input type="text" class="form-control" id="participation" name="participation" placeholder="participation" value="">
	</div>

	<button type="submit" class="btn btn-primary" name="action" value="create">Créer</button>
</form>