<h1>Créer un nouvel utilisateur</h1>
<hr>
<form method="POST">
	<div class="form-group">
		<label for="name">name</label>
		<input type="text" class="form-control" id="name" name="name" placeholder="name" value="">
	</div>
	<div class="form-group">
		<label for="nickname">Nickname</label>
		<input type="text" class="form-control" id="nickname" name="nickname" placeholder="nickname" value="">
	</div>
	<div class="form-group">
		<label for="telephone">Telephone</label>
		<input type="text" class="form-control" id="telephone" name="telephone" placeholder="telephone" value="">
	</div>
	<div class="form-group">
		<label for="adresse">Adresse</label>
		<input type="text" class="form-control" id="adresse" name="adresse" placeholder="adresse" value="">
	</div>
		<div class="form-group">
		<label for="password">Password</label>
		<input type="text" class="form-control" id="password" name="password" placeholder="password" value="">
	</div>
	</div>
		<div class="form-group">
		<label for="email">Email</label>
		<input type="text" class="form-control" id="email" name="email" placeholder="email" value="">
	</div>

	<button type="submit" class="btn btn-primary" name="action" value="create">Créer</button>
</form>