<h1>Créer un commentaire</h1>
<hr>
<form method="POST">
	<div class="form-group">
		<label for="content">Content</label>
		<input type="text" class="form-control" id="Content" name="Content" placeholder="Content" value="">
	</div>
	<div class="form-group">
		<label for="date">Date</label>
		<input type="text" class="form-control" id="date" name="date" placeholder="date" value="">
	</div>
	<div class="form-group">
		<label for="state">State</label>
		<input type="text" class="form-control" id="state" name="state" placeholder="state" value="">
	</div>

	<button type="submit" class="btn btn-primary"  name="action"value="create">Créer</button>
</form>