<h1>Créer association</h1>
<hr>
<form method="POST">
	<div class="form-group">
		<label for="description">Description</label>
		<input type="text" class="form-control" id="description" name="description" placeholder="Description" value="">
	</div>
	<div class="form-group">
		<label for="adresse">Adresse</label>
		<input type="text" class="form-control" id="adresse" name="adresse" placeholder="Adresse" value="">
	</div>
	<div class="form-group">
		<label for="nom">Nom</label>
		<input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" value="">
	</div>

	<button type="submit" class="btn btn-primary" name="action" value="create">Créer</button>
</form>
