</main>
<footer>	
<ul>
	<li>
		<a href="#">Nos partenaires</a>
					
		<a href="#">Mobilisons-nous !</a>
				
		<a href="#">Mentions légales</a>

		<a href="#">Contact</a>	

				
					
	</li>
		</ul>
		<section class="right">COPYRIGHT © 2017 Action Humanitaire Internationale® , ALL RIGHTS RESERVED.Action Humanitaire Internationale® LIABILITY, TRADEMARK, DOCUMENT USE AND SOFTWARE LICENSING RULES APPLY. YOUR INTERACTIONS WITH THIS SITE ARE IN ACCORDANCE WITH OUR PUBLIC AND MEMBER PRIVACY STATEMENTS.
		</section>
</footer>