<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Baloo+Bhaijaan" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
		<link rel="stylesheet" href="../public/css/style.css">

		<title>Action Humanitaire International ONG Humanitary International Action</title>

	</head>

	<header>
		<div class="don">
		<input id="don" type="button" value="FAIRE UN DON"/>

		</div>
		<form class="subscribe">
			<!--<a id="subscribe" href="#"> Inscription </a>-->
			
			<button id="unsigned">se déconnecter</button>
		</form>
		<h1 class="clear">Action <br>Humanitaire <br> Internationale</h1>

		
	
		<nav class="menu">
			<ul>
				<li>
					<a href="#">Accueil</a>
					
					<a href="#">Articles</a>
				
					<a href="#">Blog</a>

					<a href="#">Qui Sommes nous ?</a>	

					<a href="#">Liens utile</a>
					
				</li>
			</ul>
		</nav>

	</header>
	<main>
