
	<header>
		<div class="don">
		<input id="don" type="button" value="FAIRE UN DON"/>

		</div>
		<form class="subscribe">
			<a id="subscribe" href="index.php?page=inscription"> Inscription</a>

			<div class="bef"> Vous devez êtres inscrit pour accèder au privilèges </div>
			<input id="id" placeholder="Identifiant">

		
			<input placeholder="Mot de passe">

			<button id="validate" href="index.php?page=inscription">valider</button>
		</form>
		<h1 class="clear">Action <br>Humanitaire <br> Internationale</h1>

		
	
		<nav class="menu">
			<ul>
				<li>
					<a href="index.php?page=home">Accueil</a>
				</li>
				<li>
					<a href="index.php?page=articles">Articles</a>
				</li>
				<li>
					<a href="index.php?page=associations">Qui Sommes nous ?</a>	
				</li>
				<li>
					<a href="index.php?page=sponsors">Liens utile</a>
				</li>	
				</li>
			</ul>
		</nav>



	</header>
