<div>

	<form method="POST">

		<input type="text" id="name" name="name" placeholder="name" value="">


		<input type="text" id="nickname" name="nickname" placeholder="nickname"  value="">

	
		<input type="text" id="telephone" name="telephone" placeholder="telephone" value="">

	
		<input type="text" id="adresse" name="adresse" placeholder="adresse" value="">

		
		<input type="text" id="password" name="password" placeholder="password" value="">

		<input type="text" id="email" name="email"  placeholder="email" value="">
		<button name="action" value="create">S'inscrire</button>
	</form>

</div>