<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="./public/css/normalize.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="./public/css/style.css"/>
	<title><?= $title ?></title>
</head>
<body>
	<header>
		<?php require('./controllers/header.php'); ?>
	</header>
	<main>
		<?php require('./controllers/controllers.php'); ?>
		//main
	</main>
	<footer>
		<?php require('./controllers/footer.php'); ?>
	</footer>
</body>
</html>