<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="utf-8">
		<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Baloo+Bhaijaan" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
		<link rel="stylesheet" href="public/css/style.css">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<title>Action Humanitaire International ONG Humanitary International Action</title>

	</head>

<body>
	<header>
		<?php require('apps/header.php'); ?>
	</header>
	<main>
		<?php require('apps/container.php'); ?>
	</main>
	<footer>
		<?php require('apps/footer.php'); ?>
	</footer>
</body>
</html>