<div>

	<form method="POST">

		<input type="text" id="nom" name="nom" placeholder="nom" value="">


		<input type="text" id="description" name="description" placeholder="description"  value="">

	
		<input type="text" id="participation" name="adresse" placeholder="adresse" value="">

	
		<input type="text" id="participation" name="participation" placeholder="participation" value="">

	</form>

</div>